config/routes.rb
Rails.application.routes.draw do
  resources :groups
  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  get "guess_admin", to: "instas#guest_admin"
  get "guess", to: "instas#guest"
  devise_for :users
  get '/users_profil', to:'users#profil', as: 'profil'
  root 'instas#index'
  resources :publications do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]
  get '/publications_publication', to:'publications#publication', as: 'allpub'
  get '/publications_publi', to:'publications#publi', as: 'userpub'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :publication, optional: true
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :publication, optional: true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :publication, optional: true
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user, optional: true
  validates :content, presence: true
  mount_uploader :image, ImageUploader
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :publications, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name,  :image])
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_publication, only: [:create, :edit, :update]
  def create
    @comments = Comment.where(publication_id: @publication)
    @comment = @publication.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to publication_path(@publication) }
        format.js { render :index }
      else
        format.html { redirect_to publication_path(@publication), notice: "Couldn't post..." }
        format.js { redirect_to publication_path(@publication), notice: "Couldn't post..." }
      end
    end
  end
  def edit
    @comment = @publication.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'Editing comment'
      format.js { render :edit }
    end
  end
  def update
    @comment = @publication.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render :index }
      else
        format.js { render :edit_error }
      end
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @publication.order("created_at DESC")
    @comment.destroy
    respond_to do |format|
      #flash.now[:notice] = 'Comment deleted'
      format.html { redirect_to publication_path(@publication)}
      format.js { render :index }
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:user_id, :publication_id, :content)
    end
    def set_publication
      @publication = Publication.find(params[:publication_id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
       def index
          @favorites = current_user.favorites.all 
          puts @favorites
         end
      def create
        favorite = current_user.favorites.create(publication_id: params[:publication_id])
        redirect_to publication_path(favorite.publication), notice: "Publication ajoutée aux favories"
      end
      def destroy
        favorite = current_user.favorites.find_by(id: params[:id]).destroy
        redirect_to publication_path(favorite.publication), notice: "Publication supprimée des favories"
      end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @users= User.all
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/instas_controller.rb
class InstasController < ApplicationController
    def index
        
    end

    def guest
        @user = User.find_by(email: "guess@instafriends.com")
        unless @user
            @user = User.create!(email: "guess@instafriends.com", password: "password", is_admin: false)
        end

        sign_in @user
        redirect_to root_path, notice: "Connecter avec succès!"
    end

    def guest_admin
        @user = User.find_by(email: "admin_guess@instafriends.com")
        unless @user
            @user = User.create!(email: "admin_guess@instafriends.com", password: "password", is_admin: true)
        end
        
        sign_in @user
        redirect_to rails_admin_path if current_user.is_admin != false
        redirect_to root_path, notice: 'Accès reservé aux administrateurs' if current_user.is_admin != true
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(publication_id: params[:publication_id])
        redirect_to publication_path(like.publication), notice: "J'aime"
      end
      def destroy
        like = current_user.likes.find_by(id: params[:id]).destroy
        redirect_to publication_path(like.publication), notice: "J'aime plus"
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def profil
        @publicat = current_user.publications.all
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
    
  end

app/views/frontend/_footer.html.erb
<footer class="bg-light text-center text-lg-start fixed-bottom">
    <div class="text-right mb-2">
    <% if user_signed_in? %>
        <%= link_to "Nouvelle publications", new_publication_path, class: "btn btn-success" %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <% else %>
      
      <% end %>
      </div>
    <!-- Copyright -->
    <div class="text-center p-3" style="background: linear-gradient(to right, blue, blue, blue, blue, blue);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      © 2021 Copyright:
      <a class="text-dark" href="/">FriendShip</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
    <!-- Copyright -->
  </footer>

app/views/frontend/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-blue  mb-3" style="background: linear-gradient(to right, blue, blue, blue, blue, blue);">
    <div class="container">
        <a class="navbar-brand" href="/" style="color: black;">FriendShip</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                
                <% if user_signed_in? %>
                    <%= link_to "Accueil", root_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Groupe", groups_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Toutes les publications", allpub_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Mes Publications", userpub_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Profile", profil_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Mes Favoris", favorites_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <% if current_user.is_admin? %>
                        <%= link_to "Admin", guess_admin_path, class: "btn btn-outline-warning" %> &nbsp;&nbsp;&nbsp;
                    <% end %>
                    <%= button_to "Deconnexion", destroy_user_session_path, method: :delete, class: "btn btn-danger "%>
                <% else %> 
                    <%= link_to "Connexion", new_user_session_path, class: "btn btn-white" %> &nbsp;&nbsp;&nbsp;
                    <%= link_to "Inscription", new_user_registration_path, class: "btn btn-success" %> &nbsp;&nbsp;&nbsp;
                    <%= link_to "Invité", guess_path, class: "btn btn-warning" %> &nbsp;&nbsp;&nbsp;
                    <%= link_to "Admin invité", guess_admin_path, class: "btn btn-outline-warning" %> &nbsp;&nbsp;&nbsp;
                <% end %>                               
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>FriendShip</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
        
        <meta name="viewport" content="width=device-width,initial-scale=1">

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />
        <!-- MDB -->
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        
    <!-- Our Custom CSS -->
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    </head>
  <body style="background: #fafafa !important;">

  <%= render "frontend/header" %>
    
    <%= yield  %>
    
    <%= render "frontend/footer" %>

    <!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>

<!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
  </body>
</html>