config/routes.rb
Rails.application.routes.draw do
  resources :groups
  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  get "guess_admin", to: "instas#guest_admin"
  get "guess", to: "instas#guest"
  devise_for :users
  get '/users_profil', to:'users#profil', as: 'profil'
  root 'instas#index'
  resources :publications do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]
  get '/publications_publication', to:'publications#publication', as: 'allpub'
  get '/publications_publi', to:'publications#publi', as: 'userpub'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user, optional: true
  validates :content, presence: true
  mount_uploader :image, ImageUploader
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_publication, only: %i[ show edit update destroy ]
  
    def publication
      @publications = Publication.all
      @users = User.all
    end

    def publi
        @publicat = current_user.publications.all
        @users = User.all
    end
  
    def show 
        @comments = @publication.comments
        @comment = @publication.comments.build
        @like = current_user.likes.find_by(publication_id: @publication.id)
        @favorite = current_user.favorites.find_by(publication_id: @publication.id)
    end
  
    def new
      @publication = Publication.new
    end
  
    def edit
    end
  
    def create
      @publication = current_user.publications.build(publication_params)
      #@publication.user_id = current_user.id
      respond_to do |format|
        if @publication.save
          #PublicationMailer.published_mail(@publication).deliver
          format.html { redirect_to @publication, notice: "Publication crée avec succès." }
          format.json { render :show, status: :created, location: @publication }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @publication.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @publication.update(publication_params)
          format.html { redirect_to @publication, notice: "Publication mise à jour." }
          format.json { render :show, status: :ok, location: @publication }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @publication.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @publication.destroy
      respond_to do |format|
        format.html { redirect_to allpub_path, notice: "Publication supprimé." }
        format.json { head :no_content }
      end
    end
  
    private
    def set_publication
      @publication = Publication.find(params[:id])
    end
  
    def publication_params
      params.require(:publication).permit(:image, :image_cache, :content)
    end
end
  

app/helpers/publications_helper.rb
module PublicationsHelper
    
  end

app/views/publications/_form.html.erb
<div class="container mb-2">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 ">
            <div class="card">
                <div class="card-header text-center mt-5">
                    
                </div>
                <div class="card-body text-center">
                     
                    <%= form_with(model: @publication, local: true ) do |form| %>
                    <% if publication.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

                        <ul>
                          <% publication.errors.full_messages.each do |message| %>
                            <li style="color:red;"><%= message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="field">
                      <%= form.file_field :image %>
                      <%= form.hidden_field :image_cache %>
                    </div><br>

                    <div class="field">
                      <%= form.label :content %><br>
                      <%= form.text_area :content, placeholder: "Commentez votre image." %>
                    </div><br>

                    <div class="actions">
                      <%= form.submit "publier" %>
                    </div>
                    <% end %>
                 </div>
                 <div class="card-footer text-center mb-5">
                   <%= link_to 'Back', publications_path %>
                 </div>
             </div>
         </div>
         <div class="col-md-2"></div>
    </div>
</div>
<br></br>

app/views/publications/edit.html.erb
<div class="text-center">
	<h1>Editing Publication</h1>
</div>

<%= render 'form', publication: @publication %>
<br></br>

app/views/publications/new.html.erb
<div class="text-center">
	<h1>Nouvelle Publication</h1>
</div>

<%= render 'form', publication: @publication %>
<br></br>

app/views/publications/publi.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h2>Mes Publications</2>
</div>

<div style="margin-top: 50px;">
<% @publicat.each do |publication| %>
  
<div class="row">
  <div class="col-md-2">
    
  </div>

  <div class="col-md-8 mb-3">
      <div class="card mb-3">

    <p class="card-text mt-3">
        &nbsp;&nbsp;&nbsp;
      <i class="fas fa-user"></i>
        &nbsp;
        <% @users.each do |usere| %>
          <% if publication.user_id == usere.id %>
              <%= usere.name %>
          <% end %>
        <% end %>
        </p>
        <div class="card-body">
          <img
            src="<%= publication.image %>"
            class="card-img-top"
            alt="..."
          />
        </div>
        <div class="text-center">
          <%= publication.content %><br>
        </div><br>
        <div class="card-footer"></div>
          <div class="flex text-center">
            <% if publication.user_id == current_user.id %>
              <%= link_to 'Voir', publication %>||
              <%= link_to 'Modifier', edit_publication_path(publication) %> ||
              <%= button_to 'Supprimer', publication, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
              <%= link_to 'Voir', publication %>||
            <% end %>
          </div>
    <div class="card-body">
      
      <p class="card-text text-center" style="margin-top: -15px;">
       
      <div class="row">
        <div class="col-6 ">
          <p class="card-text">
            <small class="text-muted">Publié le <%= publication.created_at %></small>
          </p>
          <br>
        </div>
        
      </div>

    </div> 
</div>

</div>

<% end %>

</div>
<br></br>

app/views/publications/publication.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h2>Toutes Publications</h2>
</div>

<div style="margin-top: 50px;">

<% @publications.each do |publication| %>
  
<div class="row">
  <div class="col-md-2">
    
  </div>

  <div class="col-md-8 mb-3">
      <div class="card mb-3">

    <p class="card-text mt-3">
        &nbsp;&nbsp;&nbsp;
      <i class="fas fa-user"></i>
        &nbsp;
        <% @users.each do |usere| %>
          <% if publication.user_id == usere.id %>
              <%= usere.name %>
          <% end %>
        <% end %>
        </p>
        <div class="card-body">
          <img
            src="<%= publication.image %>"
            class="card-img-top"
            alt="..."
          />
        </div>
        <div class="text-center">
          <%= publication.content %><br>
        </div><br>
        <div class="card-footer"></div>
          <div class="flex text-center">
            <% if publication.user_id == current_user.id %>
              <%= link_to 'Voir', publication %>||
              <%= link_to 'Modifier', edit_publication_path(publication) %> ||
              <%= button_to 'Supprimer', publication, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
              <%= link_to 'Voir', publication %>
            <% end %>
          </div>
    <div class="card-body">
      
      <p class="card-text text-center" style="margin-top: -15px;">
       
      <div class="row">
        <div class="col-6 ">
          <p class="card-text">
            <small class="text-muted">Publié le <%= publication.created_at %></small>
          </p>
          <br>
        </div>
        
      </div>

    </div> 
</div>

</div>

<% end %>

</div>
<br></br>

app/views/publications/show.html.erb
<div class="text-center">
  <h2>Publication</2>
</div>
<div class="container mb-8">

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-right">
                
                </div>
                <div class="card-body text-center">
                     
                     <p id="notice"><%= notice %></p>
                    <p>
                      <img
                        src="<%= @publication.image %>"
                        class="img-fluid"
                        alt=""
                        style="margin-top: 30px;"
                      />
                    </p>
                    <p>
                      <%= @publication.content %>
                    </p>
                    
                 </div>
                 <div class="card-footer center d-flex">
                    <% if @like.present? %>
                      <%= button_to 'Unlike', like_path(id: @like.id), method: :delete, class: 'btn btn-danger' %>&nbsp;&nbsp;&nbsp;<i class="fas fa-heart fa-2x"></i>&nbsp;<p style="font-size:25px; color:red"><%= @publication.likes.count %></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <% else %>
                      <%= button_to 'Like', likes_path(publication_id: @publication.id), method: :post, class: 'btn btn-primary' %>&nbsp;&nbsp;&nbsp;<i class="fas fa-heart fa-2x"></i>&nbsp;<p style="font-size:25px; color:red"><%= @publication.likes.count %></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <% end %>
                    <% unless @publication.user_id == current_user.id %>
                      <% if @favorite.present? %>
                        <%= button_to 'Supprimer des favories', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-outline-danger' %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <% else %>
                        <%= button_to 'Mettre en Favorie', favorites_path(publication_id: @publication.id), method: :post, class: 'btn btn-outline-primary' %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <% end %>
                    <% end %>
                    <% if current_user.id == @publication.user_id %>
                      <%= button_to 'Modifier', edit_publication_path, method: :get  %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <%= button_to 'Supprimer', publication_path(@publication.id), method: :delete %>
                    <% end %>  
                 </div>
                 <div class="card-footer text-center">
                 <div id="comments_area">
                 <%= render partial: 'comments/index', locals: { comments: @comments, publication: @publication, user: @user } %>
                  </div>
                  <%= render partial: 'comments/form', locals: { comment: @comment, publication: @publication } %>
                  </div>
             </div>
         </div>
         <div class="col-md-1"></div>
    </div>
</div>
<br></br>