config/routes.rb
Rails.application.routes.draw do
  resources :groups
  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  get "guess_admin", to: "instas#guest_admin"
  get "guess", to: "instas#guest"
  devise_for :users
  get '/users_profil', to:'users#profil', as: 'profil'
  root 'instas#index'
  resources :publications do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy, :index]
  get '/publications_publication', to:'publications#publication', as: 'allpub'
  get '/publications_publi', to:'publications#publi', as: 'userpub'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @users= User.all
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="container mb-2">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 ">
            <div class="card">
                <div class="card-header text-center mt-5">
                    
                </div>
                <div class="card-body text-center">
                     
                <%= form_with(model: @group, local: true ) do |form| %>
                  <% if group.errors.any? %>
                    <div id="error_explanation">
                      <h2><%=pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>
                
                      <ul>
                        <% group.errors.full_messages.each do |message| %>
                          <li style="color:red;"><%= message  %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                
                  <div class="field">
                    <%= form.label :name %>
                    <%= form.text_field :name %>
                  </div>
                
                  <div class="actions">
                    <%= form.submit %>
                  </div>
                <% end %>
                 </div>
                 <div class="card-footer text-center mb-5">
                   <%= link_to 'Back', publications_path %>
                 </div>
             </div>
         </div>
         <div class="col-md-2"></div>
    </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<div style="border-radius: 5px; box-shadow: 6px 6px 6px blue;">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<div style="border-radius: 5px; box-shadow: 6px 6px 6px blue;">
<h1> Les amies disponibles </h1>
<% @users.each do |user|%>
  <% if current_user.name != user.name %>
    <strong style="color: green;"> <%= user.name%> </strong>
  <%end%>
<% end %>
</div>
<br/>
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>